### ISSUE TITLE
Issue using it in Android Instrumental Test

### ISSUE THREAD

**Issue by rocboronat** [equinox-one/fritterfactory#1]
Hi!

There's an issue using it in Instrumental test on Android. It throws a NPE:

![npe](https://cloud.githubusercontent.com/assets/456499/12509457/cc334cb8-c102-11e5-86b8-e2f486c8d50b.PNG)

Just created a branch where you can reproduce the issue. Hope it will be useful for you!
https://github.com/rocboronat/KataSuperHeroesAndroid/tree/fritter-factory-issue

BTW, thanks the library! :·)

**Comment by mateuyabar** [comment]
Hi!

Fritter Factory requires the model to have a default constructor (one with no parameters). 
I've just released a new version (0.0.3) that allows the constructor to be private.

In your case, you just need to add:
```java
private SuperHero(){}
```
and update fritter-factory library

**Comment by rocboronat** [comment]
Hum! What about explaining it in the Exception? Probably it's the best place to explain it :·)

**Comment by mateuyabar** [comment]
Yes, in the version I published yesterday the exception has a correct message (it throws a FritterFactoryException).
